### ISSUE TITLE
Images are empty

### ISSUE THREAD

**Issue by ibiBgOR** [hugovk/random-street-view#2]
I think, that google has changed it's API. Now you get an image on every request.. 
The image is empty (does not contain any image), except for the content, that says "Sorry, we got no imagery here."

I guess it is not anymore enough to just check the filesize.

**Comment by ibiBgOR** [comment]
![img_52 6349433966 -4 69840757919](https://cloud.githubusercontent.com/assets/6171670/9871305/020a413c-5b93-11e5-9891-e7ffeed7c4ab.jpg)

**Comment by hugovk** [comment]
The "no imagery" image is now 8 661 bytes. I've updated the magic constant in the code and it's working.

I suppose it could be more future-proof to instead check the size is greater than, say, 10 000 bytes. The 10 real images I just got are between 52 922 and 108 989 bytes.

Anyway, thanks for the report!
